# Lab 04 - A1
# Repeat of the Lab 03 experiments (A2 to A11) using a GenAI tool.
# GenAI tool used: Claude (Anthropic) - Claude Code CLI, model Opus 5.
# Function list, names and modularization are my own (same structure as Lab3.py);
# the body of each function below was generated by Claude as noted per section.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.spatial.distance

# A2 - encoding functions
# Code generated by Claude (Claude Code)
def label_encode(values):
    """Map each distinct category to an integer 0..n-1."""
    categories = sorted(set(values))
    mapping = {category: index for index, category in enumerate(categories)}
    return [mapping[v] for v in values], mapping

def one_hot_encode(values):
    """One row per value, one column per category, 1 in the matching column."""
    categories = sorted(set(values))
    encoded = [[int(v == category) for category in categories] for v in values]
    return encoded, categories

# A3 - encode the categorical features of marketing_campaign
# Code generated by Claude (Claude Code)
def encode_dataset(data):
    """Education -> label encoding (ordinal), Marital_Status -> one-hot (nominal)."""
    new = data.drop(columns=["Dt_Customer"])                    # date, not numeric
    new["Education"], edu_map = label_encode(list(new["Education"]))
    matrix, cols = one_hot_encode(list(new["Marital_Status"]))
    new = new.drop(columns=["Marital_Status"])
    for i, c in enumerate(cols):
        new["Marital_" + c] = [row[i] for row in matrix]
    return new, edu_map, cols

# A4 - generalized Minkowski distance (p=1 Manhattan, p=2 Euclidean)
# Code generated by Claude (Claude Code) - numpy vectorised version
def minkowski_distance(a, b, p):
    diff = np.abs(np.asarray(a, dtype=float) - np.asarray(b, dtype=float))
    return float(np.sum(diff ** p) ** (1.0 / p))

# A5 - distance for p = 1..max_p
# Code generated by Claude (Claude Code)
def minkowski_range(a, b, max_p):
    p_values = list(range(1, max_p + 1))
    distances = [minkowski_distance(a, b, p) for p in p_values]
    return p_values, distances

# A6 - own function vs scipy.spatial.distance.minkowski
# Code generated by Claude (Claude Code)
def compare_with_scipy(a, b, max_p):
    rows = []
    for p in range(1, max_p + 1):
        mine = minkowski_distance(a, b, p)
        package = scipy.spatial.distance.minkowski(a, b, p)
        rows.append([p, mine, package, abs(mine - package)])
    return rows

# A7 - dot product and Euclidean norm
# Code generated by Claude (Claude Code)
def dot_product(a, b):
    return float(sum(x * y for x, y in zip(a, b)))

def euclidean_norm(a):
    return dot_product(a, a) ** 0.5

# A8 - mean, variance, standard deviation
# Code generated by Claude (Claude Code)
def mean(data):
    return sum(data) / len(data)

def variance(data):
    m = mean(data)
    return sum((x - m) ** 2 for x in data) / len(data)

def std(data):
    return variance(data) ** 0.5

def matrix_stats(matrix):
    """Column-wise (feature-wise) mean, variance and std of a matrix."""
    columns = list(zip(*matrix))
    return ([mean(c) for c in columns],
            [variance(c) for c in columns],
            [std(c) for c in columns])

# A9 - compare A8 results with numpy
# Code generated by Claude (Claude Code)
def compare_stats(matrix):
    my_means, my_vars, my_stds = matrix_stats(matrix)
    np_means = np.mean(matrix, axis=0)
    np_stds = np.std(matrix, axis=0)
    rows = []
    for i in range(len(my_means)):
        rows.append([my_means[i], np_means[i], abs(my_means[i] - np_means[i]),
                     my_stds[i], np_stds[i], abs(my_stds[i] - np_stds[i])])
    return rows

# A10 - histogram (bucketed) data for one feature
# Code generated by Claude (Claude Code)
def histogram_data(feature, buckets):
    counts, edges = np.histogram(feature, bins=buckets)
    return counts, edges, mean(feature), variance(feature)

# A11 - k-means (Algorithm 8.1, Tan/Steinbach/Kumar section 8.2)
# Code generated by Claude (Claude Code); reuses minkowski_distance (p=2) and mean() above
def assign_clusters(matrix, centroids):
    """Step 3: assign every point to its closest centroid."""
    labels = []
    for point in matrix:
        distances = [minkowski_distance(point, c, 2) for c in centroids]
        labels.append(distances.index(min(distances)))
    return labels

def update_centroids(matrix, labels, k):
    """Step 4: recompute each centroid as the mean of its cluster."""
    centroids = []
    for cluster in range(k):
        points = [matrix[i] for i in range(len(matrix)) if labels[i] == cluster]
        if points:
            centroids.append([mean(col) for col in zip(*points)])
        else:
            centroids.append(matrix[cluster])        # empty cluster: keep a point
    return centroids

def sse(matrix, labels, centroids):
    """Sum of squared errors, used to judge the clustering quality."""
    return sum(minkowski_distance(matrix[i], centroids[labels[i]], 2) ** 2
               for i in range(len(matrix)))

def kmeans(matrix, k, max_iterations=100, seed=0):
    """Step 1-5: init centroids, then repeat assign/update until centroids stop moving."""
    rng = np.random.default_rng(seed)
    start = rng.choice(len(matrix), size=k, replace=False)
    centroids = [list(matrix[i]) for i in start]
    labels = []
    for iteration in range(1, max_iterations + 1):
        labels = assign_clusters(matrix, centroids)
        new_centroids = update_centroids(matrix, labels, k)
        if new_centroids == centroids:
            break
        centroids = new_centroids
    return centroids, labels, sse(matrix, labels, centroids), iteration


if __name__ == "__main__":
    # A2
    education = ["Graduation", "PhD", "Master", "Graduation", "Basic"]
    labels, label_map = label_encode(education)
    print("label encoded:", labels)
    print("label map:", label_map)
    one_hot_matrix, one_hot_cols = one_hot_encode(education)
    print("one hot:", one_hot_matrix)
    print("one hot columns:", one_hot_cols)

    # A3
    data = pd.read_excel("Lab Session Data (1).xlsx", sheet_name="marketing_campaign")
    encoded, edu_map, marital_cols = encode_dataset(data)
    print("education map:", edu_map)
    print("marital categories:", marital_cols)
    print("original shape:", data.shape, "-> encoded shape:", encoded.shape)
    print(encoded.head())

    # A4
    v1, v2 = [1, 2, 3], [4, 6, 8]
    print("manhattan (p=1):", minkowski_distance(v1, v2, 1))
    print("euclidean (p=2):", minkowski_distance(v1, v2, 2))
    print("p=3:", minkowski_distance(v1, v2, 3))

    # A5
    vectors = encoded.fillna(0)
    vec_a = list(vectors.iloc[0])
    vec_b = list(vectors.iloc[1])
    p_values, distances = minkowski_range(vec_a, vec_b, 10)
    for p, d in zip(p_values, distances):
        print("p =", p, "distance =", d)
    plt.plot(p_values, distances, marker="o")
    plt.xlabel("p")
    plt.ylabel("Minkowski distance")
    plt.show()

    # A6
    for p, mine, package, diff in compare_with_scipy(vec_a, vec_b, 10):
        print("p =", p, "mine =", mine, "scipy =", package, "diff =", diff)

    # A7
    print("dot mine =", dot_product(vec_a, vec_b), "numpy =", np.dot(vec_a, vec_b))
    print("norm A mine =", euclidean_norm(vec_a), "numpy =", np.linalg.norm(vec_a))
    print("norm B mine =", euclidean_norm(vec_b), "numpy =", np.linalg.norm(vec_b))

    # A8
    matrix = vectors.values.tolist()
    means, variances, stds = matrix_stats(matrix)
    print("means:", means)
    print("variances:", variances)
    print("stds:", stds)

    # A9
    for name, row in zip(vectors.columns, compare_stats(matrix)):
        print(name, "| mean mine =", row[0], "numpy =", row[1], "diff =", row[2],
              "| std mine =", row[3], "numpy =", row[4], "diff =", row[5])

    # A10
    feature = list(vectors["MntWines"])
    counts, edges, feature_mean, feature_variance = histogram_data(feature, 10)
    for i in range(len(counts)):
        print("range", edges[i], "to", edges[i + 1], "count =", counts[i])
    print("mean =", feature_mean, "variance =", feature_variance)
    plt.hist(feature, bins=10)
    plt.xlabel("MntWines")
    plt.ylabel("Frequency")
    plt.show()

    # A11
    k = 3
    centroids, cluster_labels, error, iterations = kmeans(matrix, k)
    print("k =", k, "converged in", iterations, "iterations, SSE =", error)
    for cluster in range(k):
        print("cluster", cluster, "size =", cluster_labels.count(cluster))
